import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { jsPDF } from "jspdf";
import { createReportImage } from "@/lib/utils/reportImage";

export type Step = "upload" | "adjust" | "analyzing" | "result";

export type Adjustments = {
  brightness: number;
  contrast: number;
  sharpness: number;
};

type LocationState = { openResult?: boolean };

const DEFAULT_ADJUSTMENTS: Adjustments = { brightness: 100, contrast: 100, sharpness: 100 };

export function useDoctorAnalysis() {
  const [step, setStep] = useState<Step>("upload");
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [adjustments, setAdjustments] = useState<Adjustments>(DEFAULT_ADJUSTMENTS);
  const [history, setHistory] = useState<Adjustments[]>([]);
  const activeEditRef = useRef<keyof Adjustments | null>(null);
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    const state = location.state as LocationState | null;
    if (!state?.openResult) return;
    const storedImageUrl = sessionStorage.getItem("doctorChatImageUrl");
    if (storedImageUrl) { setImageUrl(storedImageUrl); setStep("result"); }
  }, [location.state]);

  useEffect(() => {
    if (step !== "analyzing") return;
    const timer = window.setTimeout(() => setStep("result"), 5000);
    return () => window.clearTimeout(timer);
  }, [step]);

  function handleUpload(file: File) {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result;
      if (typeof result !== "string") return;
      setImageUrl(result);
      setAdjustments(DEFAULT_ADJUSTMENTS);
      setHistory([]);
      activeEditRef.current = null;
      setStep("adjust");
    };
    reader.readAsDataURL(file);
  }

  function resetSession() {
    sessionStorage.removeItem("doctorChatImageUrl");
    sessionStorage.removeItem("doctorChatImageFilter");
    setImageUrl(null);
    setAdjustments(DEFAULT_ADJUSTMENTS);
    setHistory([]);
    activeEditRef.current = null;
  }

  function handleNewScan() {
    resetSession();
    setStep("upload");
  }

  function handleBackToUpload() {
    resetSession();
    setStep("upload");
    navigate("/doctor/upload", { replace: true, state: null });
  }

  function beginAdjustment(key: keyof Adjustments) {
    if (activeEditRef.current === key) return;
    activeEditRef.current = key;
    setHistory((prev) => [...prev, adjustments]);
  }

  function finishAdjustment() { activeEditRef.current = null; }

  function updateAdjustment(key: keyof Adjustments, value: number) {
    setAdjustments((prev) => ({ ...prev, [key]: value }));
  }

  function resetAdjustments() {
    setHistory((prev) => [...prev, adjustments]);
    activeEditRef.current = null;
    setAdjustments(DEFAULT_ADJUSTMENTS);
  }

  function undoAdjustments() {
    setHistory((prev) => {
      if (prev.length === 0) return prev;
      const last = prev[prev.length - 1];
      setAdjustments(last);
      return prev.slice(0, -1);
    });
    activeEditRef.current = null;
  }

  function sendForAnalysis() { activeEditRef.current = null; setStep("analyzing"); }
  function recalculateAnalysis() { setStep("analyzing"); }

  const sharpnessBoost = adjustments.sharpness - 100;
  const imageFilter = `brightness(${adjustments.brightness + sharpnessBoost * 0.08}%) contrast(${adjustments.contrast + sharpnessBoost * 0.45}%)`;

  async function savePdf() {
    if (!imageUrl) return;
    const reportImage = await createReportImage(imageUrl, imageFilter);
    const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    pdf.setTextColor(16, 33, 36);
    pdf.setFont("times", "bold");
    pdf.setFontSize(28);
    pdf.text("MRI Scan Review", 22, 26);
    pdf.setDrawColor(74, 124, 115);
    pdf.setLineWidth(0.3);
    pdf.line(22, 36, 82, 36);
    pdf.setFontSize(14);
    pdf.text("Detected suspicious regions: 1", 22, 51);
    pdf.text("Region 1: tumor, confidence 84.2%", 22, 62);
    pdf.setFontSize(10);
    pdf.text("Note: this result does not constitute a medical diagnosis.", 22, 78);
    pdf.addImage(reportImage, "PNG", 22, 94, 125, 125);
    pdf.setFont("times", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(90, 90, 90);
    pdf.text("Generated by Tumor Eye'15.", 22, 235);
    pdf.save("mri-scan-review.pdf");
  }

  function handleChat() {
    if (imageUrl) {
      sessionStorage.setItem("doctorChatImageUrl", imageUrl);
      sessionStorage.setItem("doctorChatImageFilter", imageFilter);
    }
    navigate("/doctor/chat", { state: { imageUrl, imageFilter } });
  }

  return {
    step, imageUrl, adjustments, imageFilter,
    handleUpload, handleNewScan, handleBackToUpload,
    beginAdjustment, finishAdjustment, updateAdjustment,
    resetAdjustments, undoAdjustments, sendForAnalysis,
    recalculateAnalysis, savePdf, handleChat,
  };
}
