import { useEffect, useRef, useState, type ReactNode } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { jsPDF } from "jspdf";
import AppPanelLayout from "@/components/AppPanelLayout";

type Step = "upload" | "adjust" | "analyzing" | "result";

type Adjustments = {
  brightness: number;
  contrast: number;
  sharpness: number;
};

type LocationState = {
  openResult?: boolean;
};

const DEFAULT_ADJUSTMENTS: Adjustments = {
  brightness: 100,
  contrast: 100,
  sharpness: 100,
};

export default function DoctorAnalysis() {
  const [step, setStep] = useState<Step>("upload");
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [adjustments, setAdjustments] =
    useState<Adjustments>(DEFAULT_ADJUSTMENTS);

  const [history, setHistory] = useState<Adjustments[]>([]);
  const activeEditRef = useRef<keyof Adjustments | null>(null);

  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    const state = location.state as LocationState | null;

    if (!state?.openResult) return;

    const storedImageUrl = sessionStorage.getItem("doctorChatImageUrl");

    if (storedImageUrl) {
      setImageUrl(storedImageUrl);
      setStep("result");
    }
  }, [location.state]);

  useEffect(() => {
    if (step !== "analyzing") return;

    const timer = window.setTimeout(() => {
      setStep("result");
    }, 5000);

    return () => window.clearTimeout(timer);
  }, [step]);

  function handleUpload(file: File) {
    const reader = new FileReader();

    reader.onload = () => {
      const result = reader.result;

      if (typeof result !== "string") return;

      setImageUrl(result);
      setAdjustments(DEFAULT_ADJUSTMENTS);
      setHistory([]);
      activeEditRef.current = null;
      setStep("adjust");
    };

    reader.readAsDataURL(file);
  }

  function handleNewScan() {
    sessionStorage.removeItem("doctorChatImageUrl");
    sessionStorage.removeItem("doctorChatImageFilter");

    setImageUrl(null);
    setAdjustments(DEFAULT_ADJUSTMENTS);
    setHistory([]);
    activeEditRef.current = null;
    setStep("upload");
  }

  function handleBackToUpload() {
    sessionStorage.removeItem("doctorChatImageUrl");
    sessionStorage.removeItem("doctorChatImageFilter");

    setImageUrl(null);
    setAdjustments(DEFAULT_ADJUSTMENTS);
    setHistory([]);
    activeEditRef.current = null;
    setStep("upload");

    navigate("/doctor/upload", { replace: true, state: null });
  }

  function beginAdjustment(key: keyof Adjustments) {
    if (activeEditRef.current === key) return;

    activeEditRef.current = key;
    setHistory((prev) => [...prev, adjustments]);
  }

  function finishAdjustment() {
    activeEditRef.current = null;
  }

  function updateAdjustment(key: keyof Adjustments, value: number) {
    setAdjustments((prev) => ({
      ...prev,
      [key]: value,
    }));
  }

  function resetAdjustments() {
    setHistory((prev) => [...prev, adjustments]);
    activeEditRef.current = null;
    setAdjustments(DEFAULT_ADJUSTMENTS);
  }

  function undoAdjustments() {
    setHistory((prev) => {
      if (prev.length === 0) return prev;

      const lastAdjustment = prev[prev.length - 1];
      setAdjustments(lastAdjustment);

      return prev.slice(0, -1);
    });

    activeEditRef.current = null;
  }

  function sendForAnalysis() {
    activeEditRef.current = null;
    setStep("analyzing");
  }

  function recalculateAnalysis() {
    setStep("analyzing");
  }

  const sharpnessBoost = adjustments.sharpness - 100;

  const imageFilter = `
    brightness(${adjustments.brightness + sharpnessBoost * 0.08}%)
    contrast(${adjustments.contrast + sharpnessBoost * 0.45}%)
  `;

  async function savePdf() {
    if (!imageUrl) return;

    const reportImage = await createReportImage(imageUrl, imageFilter);

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    pdf.setTextColor(16, 33, 36);

    pdf.setFont("times", "bold");
    pdf.setFontSize(28);
    pdf.text("MRI Scan Review", 22, 26);

    pdf.setDrawColor(74, 124, 115);
    pdf.setLineWidth(0.3);
    pdf.line(22, 36, 82, 36);

    pdf.setFontSize(14);
    pdf.text("Detected suspicious regions: 1", 22, 51);
    pdf.text("Region 1: tumor, confidence 84.2%", 22, 62);

    pdf.setFontSize(10);
    pdf.text(
      "Note: this result does not constitute a medical diagnosis.",
      22,
      78
    );

    pdf.addImage(reportImage, "PNG", 22, 94, 125, 125);

    pdf.setFont("times", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(90, 90, 90);
    pdf.text("Generated by Tumor Eye'15.", 22, 235);

    pdf.save("mri-scan-review.pdf");
  }

  if (step === "analyzing") {
    return <AnalyzingScreen />;
  }

  return (
    <AppPanelLayout
      showBack={step !== "upload"}
      showLogout={step === "upload"}
      onBack={handleBackToUpload}
      title={
        step === "upload"
          ? "AI-Assisted MRI Brain Analysis"
          : step === "adjust"
          ? "Image Adjustments"
          : "MRI Scan Review"
      }
      subtitle={
        step === "upload"
          ? "Upload a brain MRI scan and generate a structured AI-supported radiology analysis."
          : undefined
      }
      sidebarContent={
        step === "adjust" ? (
          <AdjustmentsPanel
            adjustments={adjustments}
            onBeginChange={beginAdjustment}
            onFinishChange={finishAdjustment}
            onChange={updateAdjustment}
            onUndo={undoAdjustments}
            onReset={resetAdjustments}
            onSend={sendForAnalysis}
          />
        ) : step === "result" ? (
          <ResultSidebar
            onNewScan={handleNewScan}
            onRecalculate={recalculateAnalysis}
            onSavePdf={savePdf}
            onChat={() => {
              if (imageUrl) {
                sessionStorage.setItem("doctorChatImageUrl", imageUrl);
                sessionStorage.setItem("doctorChatImageFilter", imageFilter);
              }

              navigate("/doctor/chat", {
                state: {
                  imageUrl,
                  imageFilter,
                },
              });
            }}
          />
        ) : undefined
      }
    >
      {step === "upload" ? (
        <UploadArea onUpload={handleUpload} />
      ) : (
        <ImagePreview
          imageUrl={imageUrl}
          imageFilter={imageFilter}
          showDetection={step === "result"}
        />
      )}
    </AppPanelLayout>
  );
}

async function createReportImage(imageUrl: string, imageFilter: string) {
  const img = await loadImage(imageUrl);

  const canvas = document.createElement("canvas");
  canvas.width = 430;
  canvas.height = 430;

  const ctx = canvas.getContext("2d");

  if (!ctx) {
    throw new Error("Could not create canvas context.");
  }

  ctx.fillStyle = "#000000";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  const scale = Math.min(canvas.width / img.width, canvas.height / img.height);
  const drawWidth = img.width * scale;
  const drawHeight = img.height * scale;
  const drawX = (canvas.width - drawWidth) / 2;
  const drawY = (canvas.height - drawHeight) / 2;

  ctx.filter = imageFilter.replace(/\s+/g, " ").trim();
  ctx.drawImage(img, drawX, drawY, drawWidth, drawHeight);
  ctx.filter = "none";

  const boxX = canvas.width * 0.385;
  const boxY = canvas.height * 0.245;
  const boxW = canvas.width * 0.14;
  const boxH = canvas.height * 0.125;

  ctx.fillStyle = "#00ff38";
  ctx.fillRect(boxX, boxY - 22, 94, 22);

  ctx.fillStyle = "#102124";
  ctx.font = "bold 16px Georgia, serif";
  ctx.fillText("tumor 84%", boxX + 7, boxY - 7);

  ctx.strokeStyle = "#00ff38";
  ctx.lineWidth = 4;
  ctx.strokeRect(boxX, boxY, boxW, boxH);

  return canvas.toDataURL("image/png");
}

function loadImage(src: string) {
  return new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image();

    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("Could not load image."));
    img.src = src;
  });
}

function UploadArea({ onUpload }: { onUpload: (file: File) => void }) {
  return (
    <label
      className="
        w-[820px] h-[330px]
        rounded-md
        flex flex-col items-center justify-center
        cursor-pointer
        transition-opacity hover:opacity-90
      "
      style={{
        backgroundColor: "var(--c-panel)",
        color: "var(--c-text)",
      }}
    >
      <input
        type="file"
        accept="image/*,.png,.jpg,.jpeg"
        className="hidden"
        onChange={(event) => {
          const file = event.target.files?.[0];

          if (file) {
            onUpload(file);
          }
        }}
      />

      <span
        className="
          w-[34px] h-[34px]
          rounded-sm
          border
          flex items-center justify-center
          text-[30px] leading-none
          mb-[14px]
        "
        style={{
          borderColor: "var(--c-text)",
          color: "var(--c-text)",
        }}
      >
        +
      </span>

      <span className="text-[20px] font-bold text-center">
        Upload brain MRI scan
      </span>

      <span className="text-[15px] font-semibold opacity-70 mt-[8px]">
        Click or drag file to upload
      </span>
    </label>
  );
}

function ImagePreview({
  imageUrl,
  imageFilter,
  showDetection,
}: {
  imageUrl: string | null;
  imageFilter: string;
  showDetection: boolean;
}) {
  return (
    <div className="relative w-[520px] h-[520px] flex items-center justify-center">
      <div
        className="relative w-[430px] h-[430px] flex items-center justify-center"
        style={{ backgroundColor: "#000" }}
      >
        {imageUrl ? (
          <img
            src={imageUrl}
            alt="MRI scan"
            className="w-full h-full object-contain"
            style={{ filter: imageFilter }}
          />
        ) : (
          <p className="text-white text-[14px] font-bold">No image selected</p>
        )}

        {showDetection && <DetectionBox />}
      </div>
    </div>
  );
}

function DetectionBox() {
  return (
    <div
      className="absolute pointer-events-none"
      style={{
        left: "40.5%",
        top: "25.8%",
        width: "14%",
        height: "12.5%",
        overflow: "visible",
      }}
    >
      <div
        className="absolute flex items-center justify-center"
        style={{
          left: 0,
          bottom: "calc(100% - 2px)",
          minWidth: "100%",
          height: "16px",
          padding: "0 6px",
          backgroundColor: "#00ff38",
          color: "#102124",
          fontSize: "10px",
          fontWeight: 700,
          lineHeight: 1,
          whiteSpace: "nowrap",
          boxSizing: "border-box",
          zIndex: 2,
        }}
      >
        Tumor 84%
      </div>

      <div
        className="absolute inset-0"
        style={{
          border: "2px solid #00ff38",
          boxSizing: "border-box",
        }}
      />
    </div>
  );
}

function ResultSidebar({
  onNewScan,
  onRecalculate,
  onSavePdf,
  onChat,
}: {
  onNewScan: () => void;
  onRecalculate: () => void;
  onSavePdf: () => void;
  onChat: () => void;
}) {
  return (
    <div
      className="w-[230px] flex-1 flex flex-col pt-[2px]"
      style={{ color: "var(--c-sidebar-text)" }}
    >
      <div>
        <div className="text-[15px] font-extrabold leading-[1.45]">
          <p>Detected suspicious regions: 1</p>

          <p className="mt-[8px]">Region 1: tumor, confidence 84.2%</p>
        </div>

        <p className="mt-[28px] text-[11px] font-bold leading-[1.35] max-w-[190px]">
          Note: this result does not constitute a medical diagnosis.
        </p>
      </div>

      <div className="mt-auto flex flex-col gap-[16px]">
        <SideButton onClick={onNewScan}>New scan</SideButton>
        <SideButton onClick={onRecalculate}>Recalculate</SideButton>
        <SideButton onClick={onSavePdf}>Save PDF</SideButton>
        <SideButton onClick={onChat}>Chat with AI</SideButton>
      </div>
    </div>
  );
}

function AdjustmentsPanel({
  adjustments,
  onBeginChange,
  onFinishChange,
  onChange,
  onUndo,
  onReset,
  onSend,
}: {
  adjustments: Adjustments;
  onBeginChange: (key: keyof Adjustments) => void;
  onFinishChange: () => void;
  onChange: (key: keyof Adjustments, value: number) => void;
  onUndo: () => void;
  onReset: () => void;
  onSend: () => void;
}) {
  return (
    <div className="mt-[0px] w-[232px] flex-1 flex flex-col">
      <div className="flex flex-col gap-[16px]">
        <Slider
          sliderKey="brightness"
          label="Brightness"
          value={adjustments.brightness}
          min={50}
          max={150}
          onBeginChange={onBeginChange}
          onFinishChange={onFinishChange}
          onChange={onChange}
        />

        <Slider
          sliderKey="contrast"
          label="Contrast"
          value={adjustments.contrast}
          min={50}
          max={160}
          onBeginChange={onBeginChange}
          onFinishChange={onFinishChange}
          onChange={onChange}
        />

        <Slider
          sliderKey="sharpness"
          label="Sharpness"
          value={adjustments.sharpness}
          min={50}
          max={150}
          onBeginChange={onBeginChange}
          onFinishChange={onFinishChange}
          onChange={onChange}
        />
      </div>

      <div className="mt-[36px] flex flex-col gap-[16px]">
        <SideButton onClick={onUndo}>Undo</SideButton>
        <SideButton onClick={onReset}>Reset</SideButton>
        <SideButton onClick={onSend}>Send for analysis</SideButton>
      </div>
    </div>
  );
}

function Slider({
  sliderKey,
  label,
  value,
  min,
  max,
  onBeginChange,
  onFinishChange,
  onChange,
}: {
  sliderKey: keyof Adjustments;
  label: string;
  value: number;
  min: number;
  max: number;
  onBeginChange: (key: keyof Adjustments) => void;
  onFinishChange: () => void;
  onChange: (key: keyof Adjustments, value: number) => void;
}) {
  return (
    <label className="block w-[232px]">
      <span
        className="block text-[17px] font-extrabold mb-[8px]"
        style={{ color: "var(--c-sidebar-text)" }}
      >
        {label}
      </span>

      <input
        type="range"
        min={min}
        max={max}
        value={value}
        onPointerDown={() => onBeginChange(sliderKey)}
        onPointerUp={onFinishChange}
        onMouseUp={onFinishChange}
        onTouchEnd={onFinishChange}
        onBlur={onFinishChange}
        onKeyDown={(event) => {
          if (
            event.key === "ArrowLeft" ||
            event.key === "ArrowRight" ||
            event.key === "ArrowUp" ||
            event.key === "ArrowDown"
          ) {
            onBeginChange(sliderKey);
          }
        }}
        onKeyUp={onFinishChange}
        onChange={(event) => onChange(sliderKey, Number(event.target.value))}
        className="w-[232px] h-[9px] cursor-pointer"
        style={{
          accentColor: "#4a7c73",
        }}
      />
    </label>
  );
}

function SideButton({
  children,
  onClick,
}: {
  children: ReactNode;
  onClick?: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="
        w-[232px] h-[50px]
        rounded-sm
        border-none
        cursor-pointer
        text-[16px]
        font-extrabold
        transition-opacity
        hover:opacity-90
      "
      style={{
        backgroundColor: "#4a7c73",
        color: "#1c2b2e",
      }}
    >
      {children}
    </button>
  );
}

function AnalyzingScreen() {
  return (
    <div
      className="w-screen h-screen overflow-hidden flex items-center justify-center"
      style={{
        backgroundColor: "var(--c-bg)",
        fontFamily: "Abhaya Libre, serif",
      }}
    >
      <style>{`
        @keyframes analyzingPulseOuter {
          0%, 100% {
            transform: translate(-50%, -50%) scale(0.96);
            opacity: 0.22;
          }
          50% {
            transform: translate(-50%, -50%) scale(1.04);
            opacity: 0.6;
          }
        }

        @keyframes analyzingPulseMiddle {
          0%, 100% {
            transform: translate(-50%, -50%) scale(0.97);
            opacity: 0.35;
          }
          50% {
            transform: translate(-50%, -50%) scale(1.03);
            opacity: 0.8;
          }
        }

        @keyframes analyzingPulseInner {
          0%, 100% {
            transform: translate(-50%, -50%) scale(0.98);
            opacity: 0.45;
          }
          50% {
            transform: translate(-50%, -50%) scale(1.02);
            opacity: 1;
          }
        }

        @keyframes analyzingCenterPulse {
          0%, 100% {
            transform: translate(-50%, -50%) scale(0.92);
            opacity: 0.85;
          }
          50% {
            transform: translate(-50%, -50%) scale(1.08);
            opacity: 1;
          }
        }

        @keyframes analyzingSpin {
          from {
            transform: rotate(0deg);
          }
          to {
            transform: rotate(360deg);
          }
        }

        @keyframes analyzingSpinReverse {
          from {
            transform: rotate(360deg);
          }
          to {
            transform: rotate(0deg);
          }
        }

        @keyframes analyzingDotPulse {
          0%, 100% {
            opacity: 0.35;
            transform: scale(0.8);
          }
          50% {
            opacity: 1;
            transform: scale(1.15);
          }
        }

        @keyframes analyzingTextPulse {
          0%, 100% {
            opacity: 0.75;
          }
          50% {
            opacity: 1;
          }
        }
      `}</style>

      <div className="flex flex-col items-center justify-center">
        <div className="relative w-[250px] h-[250px]">
          <span
            className="absolute left-1/2 top-1/2 rounded-full"
            style={{
              width: 174,
              height: 174,
              border: "1px solid var(--c-accent)",
              animation: "analyzingPulseOuter 2.8s ease-in-out infinite",
            }}
          />

          <span
            className="absolute left-1/2 top-1/2 rounded-full"
            style={{
              width: 144,
              height: 144,
              border: "1px solid var(--c-accent)",
              animation: "analyzingPulseMiddle 2.2s ease-in-out infinite",
            }}
          />

          <span
            className="absolute left-1/2 top-1/2 rounded-full"
            style={{
              width: 108,
              height: 108,
              border: "2px solid var(--c-accent)",
              animation: "analyzingPulseInner 1.8s ease-in-out infinite",
            }}
          />

          <span
            className="absolute left-1/2 top-1/2 rounded-full"
            style={{
              width: 66,
              height: 66,
              border: "2px solid var(--c-accent)",
              animation: "analyzingPulseInner 1.6s ease-in-out infinite",
            }}
          />

          <span
            className="absolute left-1/2 top-1/2 rounded-full"
            style={{
              width: 52,
              height: 52,
              backgroundColor: "var(--c-accent)",
              animation: "analyzingCenterPulse 1.4s ease-in-out infinite",
            }}
          />

          <div
            className="absolute inset-0"
            style={{ animation: "analyzingSpin 8s linear infinite" }}
          >
            <span
              className="absolute left-1/2 top-[38px] -translate-x-1/2 rounded-full"
              style={{
                width: 7,
                height: 7,
                backgroundColor: "var(--c-accent)",
                animation: "analyzingDotPulse 1.5s ease-in-out infinite",
              }}
            />
          </div>

          <div
            className="absolute inset-0"
            style={{ animation: "analyzingSpinReverse 6.5s linear infinite" }}
          >
            <span
              className="absolute left-[42px] top-1/2 -translate-y-1/2 rounded-full"
              style={{
                width: 6,
                height: 6,
                backgroundColor: "var(--c-accent)",
                animation: "analyzingDotPulse 1.7s ease-in-out infinite",
              }}
            />
          </div>

          <div
            className="absolute inset-0"
            style={{ animation: "analyzingSpin 5.7s linear infinite" }}
          >
            <span
              className="absolute left-1/2 bottom-[56px] -translate-x-1/2 rounded-full"
              style={{
                width: 6,
                height: 6,
                backgroundColor: "var(--c-accent)",
                animation: "analyzingDotPulse 1.3s ease-in-out infinite",
              }}
            />
          </div>

          <div
            className="absolute inset-0"
            style={{ animation: "analyzingSpinReverse 4.8s linear infinite" }}
          >
            <span
              className="absolute right-[58px] top-1/2 -translate-y-1/2 rounded-full"
              style={{
                width: 5,
                height: 5,
                backgroundColor: "var(--c-accent)",
                animation: "analyzingDotPulse 1.2s ease-in-out infinite",
              }}
            />
          </div>
        </div>

        <p
          className="mt-[2px] text-[36px] font-bold"
          style={{
            color: "var(--c-accent)",
            animation: "analyzingTextPulse 1.8s ease-in-out infinite",
          }}
        >
          Analyzing...
        </p>
      </div>
    </div>
  );
}